## Binder quick start (safe defaults)

- Optional: set `INAT_TOKEN` in this session for higher limits.
- Start with low-traffic settings: `per_page=25`, `max_pages=2`, `fetch_images=False`.
- This notebook runs without a token (anonymous), but may be rate-limited.

In [1]:
import os
#from pynat.helpers import coming_soon, get_park_data
from helpers import coming_soon, get_park_data

INAT_TOKEN_SET = bool(os.getenv("INAT_TOKEN"))
print(f"INAT token set: {INAT_TOKEN_SET}")
print("Low-traffic defaults: per_page=25, max_pages=2, fetch_images=False")

# Example usage (uncomment to run)
# df = coming_soon(
#     "birds",
#     loc=(37.6669, -77.8883, 25),
#     per_page=25,
#     max_pages=2,
#     fetch_images=False,
# )
# display(df.head(20))

INAT token set: False
Low-traffic defaults: per_page=25, max_pages=2, fetch_images=False

In [2]:
import pandas as pd
import pyinaturalist as inat

In [3]:
# get geogenters for all parks

parks = {
    'tucker': (37.66713, -77.88739, 0.4), 
    'hiddenrock': (37.70219, -77.87333, 0.63), 
    'leakesmill': (37.70678, -77.95971, 0.68), 
    'matthews': (37.78714, -78.03979, 0.34),
}

In [4]:
res = {}
for park in parks:
    pagenum = 0
    res[park] = pd.DataFrame()
    while(True):
        pagenum += 1
        tmp = pd.json_normalize(inat.get_observation_species_counts(lat=parks[park][0], 
                                                                    lng=parks[park][1], 
                                                                    radius=parks[park][2], 
                                                                    verifiable=True,
                                                                    #capitve
                                                                    #introduced
                                                                    #native
                                                                    #endemic
                                                                    #threatened
                                                                    page=pagenum,
                                                                   )['results'])
        if tmp.empty:
            break
        res[park] = pd.concat([res[park], tmp])    
    normer = pd.json_normalize(inat.get_observation_species_counts(taxon_id=res[park]['taxon.id'].to_list(),
                                                                   place_id=1297, # relative to Virginia
                                                                   verifiable=True,
                                                                  )['results'])
    res[park]['normalizer'] = res[park]['taxon.id'].map(normer.set_index('taxon.id')['count'])
    res[park]['sorter'] = res[park]['count']/res[park]['normalizer']
    res[park].sort_values('sorter', ascending=False, inplace=True)

### suspicious that so many of these max at 500...

In [5]:
for park in parks:
    print(f"{park}: {res[park].shape}")

tucker: (593, 45)
hiddenrock: (218, 36)
leakesmill: (270, 45)
matthews: (72, 36)

In [6]:
res['tucker'][['count', 'taxon.name', 'taxon.preferred_common_name', 'taxon.wikipedia_url']].sort_values('count', ascending=False).head(25)

,count,taxon.name,taxon.preferred_common_name,taxon.wikipedia_url
0,34,Sialia sialis,Eastern Bluebird,http://en.wikipedia.org/wiki/Eastern_bluebird
1,31,Argia apicalis,Blue-fronted Dancer,http://en.wikipedia.org/wiki/Blue-fronted_dancer
2,31,Argia moesta,Powdered Dancer,http://en.wikipedia.org/wiki/Powdered_dancer
3,30,Hetaerina titia,Smoky Rubyspot,http://en.wikipedia.org/wiki/Hetaerina_titia
4,30,Ligustrum sinense,Chinese privet,http://en.wikipedia.org/wiki/Ligustrum_sinense
5,24,Rosa multiflora,multiflora rose,http://en.wikipedia.org/wiki/Rosa_multiflora
7,19,Cyprinella analostana,Satinfin Shiner,http://en.wikipedia.org/wiki/Satinfin_shiner
8,19,Humulus scandens,Japanese Hops,http://en.wikipedia.org/wiki/Humulus_japonicus
6,19,Eupatorium serotinum,late boneset,http://en.wikipedia.org/wiki/Eupatorium_serotinum
9,17,Verbesina alternifolia,Wingstem,http://en.wikipedia.org/wiki/Verbesina_alterni...
11,16,Euonymus fortunei,fortune's spindle,http://en.wikipedia.org/wiki/Euonymus_fortunei
10,16,Hetaerina americana,American Rubyspot,http://en.wikipedia.org/wiki/American_rubyspot
12,15,Erpetogomphus designatus,Eastern Ringtail,http://en.wikipedia.org/wiki/Erpetogomphus_des...
13,14,Micropterus dolomieu,Smallmouth Bass,http://en.wikipedia.org/wiki/Smallmouth_bass
15,13,Toxicodendron radicans,eastern poison ivy,http://en.wikipedia.org/wiki/Toxicodendron_rad...
14,13,Alliaria petiolata,garlic mustard,http://en.wikipedia.org/wiki/Alliaria_petiolata
20,12,Setophaga coronata,Yellow-rumped Warbler,http://en.wikipedia.org/wiki/Yellow-rumped_war...
16,12,Zonotrichia albicollis,White-throated Sparrow,https://en.wikipedia.org/wiki/White-throated_s...
18,12,Glechoma hederacea,ground-ivy,http://en.wikipedia.org/wiki/Glechoma_hederacea
17,12,Conium maculatum,poison hemlock,http://en.wikipedia.org/wiki/Conium_maculatum
19,12,Sambucus canadensis,American black elderberry,http://en.wikipedia.org/wiki/Sambucus_canadensis
22,11,Melospiza melodia,Song Sparrow,http://en.wikipedia.org/wiki/Song_sparrow
21,11,Cardinalis cardinalis,Northern Cardinal,http://en.wikipedia.org/wiki/Northern_cardinal
23,11,Tachycineta bicolor,Tree Swallow,http://en.wikipedia.org/wiki/Tree_swallow
29,10,Argia sedula,Blue-ringed Dancer,https://en.wikipedia.org/wiki/Argia_sedula

In [7]:
res['leakesmill'][['count', 'taxon.name', 'taxon.preferred_common_name', 'taxon.wikipedia_url']].sort_values('count', ascending=False).head(25)

,count,taxon.name,taxon.preferred_common_name,taxon.wikipedia_url
0,20,Hepatica americana,round-lobed hepatica,http://en.wikipedia.org/wiki/Hepatica_nobilis
1,12,Aplectrum hyemale,putty root,https://en.wikipedia.org/wiki/Aplectrum
2,12,Erythronium umbilicatum,dimpled trout lily,http://en.wikipedia.org/wiki/Erythronium_umbil...
3,11,Tipularia discolor,crane-fly orchid,https://en.wikipedia.org/wiki/Tipularia_discolor
4,10,Packera aurea,golden ragwort,http://en.wikipedia.org/wiki/Packera_aurea
5,10,Claytonia virginica,Virginia Springbeauty,https://en.wikipedia.org/wiki/Claytonia_virginica
7,10,Stellaria pubera,star chickweed,http://en.wikipedia.org/wiki/Stellaria_pubera
6,10,Thalictrum thalictroides,rue anemone,http://en.wikipedia.org/wiki/Thalictrum_thalic...
9,9,Asarum virginicum,Virginia heartleaf,https://en.wikipedia.org/wiki/Hexastylis_virgi...
8,9,Diphasiastrum digitatum,fan clubmoss,http://en.wikipedia.org/wiki/Diphasiastrum_dig...
10,8,Athyrium asplenioides,southern lady fern,http://en.wikipedia.org/wiki/Athyrium_asplenio...
12,7,Lindera benzoin,northern spicebush,http://en.wikipedia.org/wiki/Lindera_benzoin
11,7,Polystichum acrostichoides,Christmas fern,http://en.wikipedia.org/wiki/Polystichum_acros...
13,6,Lonicera japonica,Japanese honeysuckle,https://en.wikipedia.org/wiki/Lonicera_japonica
15,5,Geum canadense,white avens,http://en.wikipedia.org/wiki/Geum_canadense
14,5,Goodyera pubescens,downy rattlesnake plantain,http://en.wikipedia.org/wiki/Goodyera_pubescens
16,5,Houstonia pusilla,tiny bluet,http://en.wikipedia.org/wiki/Houstonia_pusilla
22,4,Ilex decidua,possumhaw,http://en.wikipedia.org/wiki/Ilex_decidua
23,4,Chrysopsis mariana,Maryland golden-aster,http://en.wikipedia.org/wiki/Chrysopsis_mariana
24,4,Asarum minus,little heartleaf,https://en.wikipedia.org/wiki/Asarum_minus
17,4,Acer negundo,box elder,http://en.wikipedia.org/wiki/Acer_negundo
21,4,Rosa multiflora,multiflora rose,http://en.wikipedia.org/wiki/Rosa_multiflora
18,4,Platanus occidentalis,American sycamore,http://en.wikipedia.org/wiki/Platanus_occident...
19,4,Cardamine concatenata,cut-leaved toothwort,https://en.wikipedia.org/wiki/Cardamine_concat...
20,4,Papilio glaucus,Eastern Tiger Swallowtail,http://en.wikipedia.org/wiki/Papilio_glaucus

In [8]:
res['hiddenrock'][['count', 'taxon.name', 'taxon.preferred_common_name', 'taxon.wikipedia_url']].sort_values('count', ascending=False).head(25)

,count,taxon.name,taxon.preferred_common_name,taxon.wikipedia_url
0,11,Lobelia inflata,Indian tobacco,https://en.wikipedia.org/wiki/Lobelia_inflata
1,9,Diphasiastrum digitatum,fan clubmoss,http://en.wikipedia.org/wiki/Diphasiastrum_dig...
2,8,Arisaema triphyllum,Jack-in-the-Pulpit,http://en.wikipedia.org/wiki/Arisaema_triphyllum
3,8,Lindera benzoin,northern spicebush,http://en.wikipedia.org/wiki/Lindera_benzoin
5,7,Elaeagnus umbellata,autumn olive,http://en.wikipedia.org/wiki/Elaeagnus_umbellata
4,7,Podophyllum peltatum,mayapple,https://en.wikipedia.org/wiki/Podophyllum
10,5,Packera aurea,golden ragwort,http://en.wikipedia.org/wiki/Packera_aurea
11,5,Microstegium vimineum,Japanese stiltgrass,http://en.wikipedia.org/wiki/Microstegium_vimi...
8,5,Saururus cernuus,lizard's tail,http://en.wikipedia.org/wiki/Saururus_cernuus
7,5,Corylus americana,American hazelnut,https://en.wikipedia.org/wiki/Corylus_americana
9,5,Calopteryx maculata,Ebony Jewelwing,http://en.wikipedia.org/wiki/Ebony_jewelwing
6,5,Monotropa uniflora,Ghost Pipe,http://en.wikipedia.org/wiki/Monotropa_uniflora
20,4,Cantharellus cinnabarinus,Red Chanterelle,http://en.wikipedia.org/wiki/Cantharellus_cinn...
22,4,Hylodesmum nudiflorum,naked-flowered tick-trefoil,https://en.wikipedia.org/wiki/Hylodesmum_nudif...
15,4,Libellula incesta,Slaty Skimmer,http://en.wikipedia.org/wiki/Libellula_incesta
14,4,Geum canadense,white avens,http://en.wikipedia.org/wiki/Geum_canadense
12,4,Trametes versicolor,turkey-tail,https://en.wikipedia.org/wiki/Trametes_versicolor
17,4,Sceptridium dissectum,Cutleaf Grapefern,http://en.wikipedia.org/wiki/Sceptridium_disse...
18,4,Houstonia pusilla,tiny bluet,http://en.wikipedia.org/wiki/Houstonia_pusilla
16,4,Woodwardia areolata,netted chain fern,https://en.wikipedia.org/wiki/Lorinseria
21,4,Smallanthus uvedalia,bear's foot,https://en.wikipedia.org/wiki/Smallanthus_uved...
19,4,Commelina virginica,Virginia Dayflower,http://en.wikipedia.org/wiki/Commelina_virginica
23,4,Berberis bealei,leatherleaf mahonia,https://en.wikipedia.org/wiki/Mahonia_bealei
13,4,Toxicodendron radicans,eastern poison ivy,http://en.wikipedia.org/wiki/Toxicodendron_rad...
29,3,Boehmeria cylindrica,false nettle,http://en.wikipedia.org/wiki/Boehmeria_cylindrica

In [9]:
res['matthews'][['count', 'taxon.name', 'taxon.preferred_common_name', 'taxon.wikipedia_url']].sort_values('count', ascending=False).head(25)

,count,taxon.name,taxon.preferred_common_name,taxon.wikipedia_url
2,2,Erynnis juvenalis,Juvenal's Duskywing,http://en.wikipedia.org/wiki/Erynnis_juvenalis
1,2,Prunus serotina,black cherry,https://en.wikipedia.org/wiki/Prunus_serotina
3,2,Lonicera japonica,Japanese honeysuckle,https://en.wikipedia.org/wiki/Lonicera_japonica
4,2,Rubus pensilvanicus,Pennsylvania Blackberry,http://en.wikipedia.org/wiki/Rubus_pensilvanicus
0,2,Acer rubrum,red maple,http://en.wikipedia.org/wiki/Acer_rubrum
5,2,Diastrophus nebulosus,Blackberry Knot Gall Wasp,https://en.wikipedia.org/wiki/Diastrophus_nebu...
43,1,Chimaphila maculata,striped wintergreen,http://en.wikipedia.org/wiki/Chimaphila_maculata
21,1,Poa annua,Annual Meadow-grass,http://en.wikipedia.org/wiki/Poa_annua
64,1,Acericecis ocellaris,Ocellate Gall Midge,http://en.wikipedia.org/wiki/Acericecis_ocellaris
46,1,Mitchella repens,partridgeberry,http://en.wikipedia.org/wiki/Mitchella_repens
61,1,Carex glaucodea,Blue Sedge,NaN
60,1,Hylodesmum nudiflorum,naked-flowered tick-trefoil,https://en.wikipedia.org/wiki/Hylodesmum_nudif...
47,1,Vaccinium pallidum,Early Lowbush Blueberry,http://en.wikipedia.org/wiki/Vaccinium_pallidum
37,1,Ilex opaca,American holly,http://en.wikipedia.org/wiki/Ilex_opaca
30,1,Morus rubra,red mulberry,http://en.wikipedia.org/wiki/Morus_rubra
66,1,Strobilomyces strobilaceus,Old-man-of-the-woods,https://en.wikipedia.org/wiki/Strobilomyces_st...
33,1,Juncus effusus,Soft Rush,http://en.wikipedia.org/wiki/Juncus_effusus
50,1,Reticulitermes flavipes,Eastern Subterranean Termite,http://en.wikipedia.org/wiki/Eastern_subterran...
32,1,Veronica persica,bird's-eye speedwell,http://en.wikipedia.org/wiki/Veronica_persica
59,1,Viburnum recognitum,northern arrowwood,https://en.wikipedia.org/wiki/Viburnum_recognitum
7,1,Sayornis phoebe,Eastern Phoebe,http://en.wikipedia.org/wiki/Eastern_phoebe
68,1,Exidia crenata,American Amber Jelly Fungus,https://en.wikipedia.org/wiki/Exidia_crenata
52,1,Diphasiastrum digitatum,fan clubmoss,http://en.wikipedia.org/wiki/Diphasiastrum_dig...
51,1,Lactarius indigo,indigo milk cap,http://en.wikipedia.org/wiki/Lactarius_indigo
6,1,Pipilo erythrophthalmus,Eastern Towhee,http://en.wikipedia.org/wiki/Eastern_towhee

In [ ]:
# highlight unusual species esp. engagered ones (sum and check trends)

In [ ]:
# highlight unusual or *unusually-increasing* invasives (sum and check trends)